name: Build/release

on: push

jobs:
    release:
        runs-on: debian

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v1

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Update dependencies
              run: |
                  yarn upgrade @suen/music-api @suen/electron-updater

            - name: Build/release Electron app
              uses: samuelmeuli/action-electron-builder@v1
              with:
                  # GitHub token, automatically provided to the action
                  # (No need to define this secret in the repo settings)
                  github_token: ${{ secrets.github_token }}
                  mac_certs: ${{ secrets.mac_certs }}
                  mac_certs_password: ${{ secrets.mac_certs_password }}

                  # If the commit is tagged with a version (e.g. "v1.0.0"),
                  # release the app after building
                  release: ${{ startsWith(github.ref, 'refs/tags/v') }}
                  build_script_name: build-file
